// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtpK4XZZrDDVEvlWPzXZ0REMnF_yvHImI',
    appId: '1:355847532999:web:3c8d43951d7b32d5da29e2',
    messagingSenderId: '355847532999',
    projectId: 'timkasir-firebase',
    authDomain: 'timkasir-firebase.firebaseapp.com',
    databaseURL: 'https://timkasir-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timkasir-firebase.appspot.com',
    measurementId: 'G-6G5F83EL9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMbI6enXTVC0MELAcivJeqplfgIAwwnbM',
    appId: '1:355847532999:android:f009bc5f484cf4d4da29e2',
    messagingSenderId: '355847532999',
    projectId: 'timkasir-firebase',
    databaseURL: 'https://timkasir-firebase-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'timkasir-firebase.appspot.com',
  );
}
